[[main]]
  name = "Services"
  url = "/services/"
  weight = 1

[[main]]
  name = "Research"
  url = "/research/"
  weight = "2"

[[main]]
  name = "Publications"
  url = "/publications/"
  weight = "3"

[[main]]
  name = "Software"
  url = "/software/"
  weight = "4"

[[main]]
  name = "Team"
  identifier = "team"
  url = "/team/"
  weight = "5"

[[main_right]]
  url = "mailto:contact@dapperstats.com"
  name = "<i class='fa fa-envelope'></i>"
  identifier = "mail"
  weight = 1

[[main_right]]
  url = "https://www.github.com/dapperstats"
  name = "<i class='fab fa-github-alt'></i>"
  identifier = "github"
  weight = 2

[[main_right]]
  url = "https://www.twitter.com/dapperstats"
  name = "<i class='fab fa-twitter'></i>"
  identifier = "twitter"
  weight = 3