baseurl = "/"
languageCode = "en-us"
title = "DAPPER Stats - on-point quantitative analysis and data solutions"
theme = "dapperstats"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = "1"
[[menu.main]]
    name = "Services"
    url = "/services/"
    weight = "2"
[[menu.main]]
    name = "Positions"
    url = "/positions/"
    weight = "3"
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = "4"

[params]
    description = "On-point quantitative analysis and data solutions."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo_header.png"
    width = 240
    height = 105
    alt = "DAPPER Stats - Logo"

